name: Publish

on:
  workflow_dispatch:

concurrency:
  group: "publish"

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup JDK
            uses: actions/setup-java@v4
            with:
                distribution: temurin
                java-version: 21

          - name: Elevate Wrapper Perms
            run: chmod +x ./gradlew

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@v4

          - name: Publish
            env:
                MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
                PUBLISH_VERSION: ${{ github.run_number }}
            run: ./gradlew build publishReleasePublicationToVcRepository
